################################################################################
### generated-with:
###   type: R-package
###   name: kwb.pkgbuild
###   version: 0.1.7
###   installed-from: Github (kwb-r/kwb.pkgbuild@c429bfd)
###   installed-on: '2021-03-04'
### generated-by:
###   user: mrustl
###   function-call: kwb.pkgbuild::create_empty_branch_ghpages(repo = "appifyr", org =
###     "mrustl")
### generated-on: 2021-05-31 10:14:43
################################################################################


pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - gh-pages
